{{- $global := .Values.global | default dict }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.controllerPlaneFlags }}
  controllerPlaneFlags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $global.registry }}
  image: {{ $global.registry }}/k0sproject/k0s
  etcd:
    image: "{{ $global.registry }}/k0sproject/etcd:v3.5.13"
  {{- if $global.registryCertSecret }}
  mounts:
    - path: /usr/local/share/ca-certificates/registry
      secret:
        defaultMode: 420
        items:
          - key: ca.crt
            path: ca.crt
        secretName: {{ $global.registryCertSecret }}
  {{- end }}
  {{- end }}
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      {{- with .Values.k0s.api.extraArgs }}
      api:
        extraArgs:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.k0s.network }}
      network:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $global.registry }}
      images:
        repository: {{ $global.registry }}
      {{- end }}
      extensions:
        helm:
          {{- with .Values.k0s.extensions.helm.repositories }}
          repositories:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.k0s.extensions.helm.charts }}
          charts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  persistence:
    type: emptyDir
