{{- $global := .Values.global | default dict }}
{{- range $machine := .Values.machines }}
{{- $shaSum := sha256sum (printf "%s%s" $machine.address $machine.port) | trunc 6 }}
{{- $defaultName := printf "%s-%s" (include "cluster.name" $) $shaSum -}}
{{- $name := default $defaultName $machine.name -}}
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: {{ $name }}
spec:
  clusterName: {{ include "cluster.name" $ }}
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
      kind: K0sWorkerConfig
      name: {{ $name }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: RemoteMachine
    name: {{ $name }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfig
metadata:
  name: {{ $name }}
  annotations:
    # Temporary fix to address https://github.com/k0sproject/k0smotron/issues/942
    # to prevent premature K0sWorkerConfig deletion
    helm.sh/resource-policy: keep
spec:
  version: {{ $.Values.k0s.version }}
  {{- if $global.k0sURL }}
  downloadURL: "{{ $global.k0sURL }}/k0s-{{ $.Values.k0s.version }}-{{ $.Values.k0s.arch }}"
  {{- end }}
  {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
  {{- $certs := dict "registry.crt" $global.registryCertSecret "k0s-url.crt" $global.k0sURLCertSecret }}
  files:
    {{- range $path, $secret := $certs }}
    {{- if $secret }}
    - contentFrom:
        secretRef:
          name: {{ $secret }}
          key: ca.crt
      permissions: "0664"
      path: /usr/local/share/ca-certificates/{{ $path }}
    {{- end }}
    {{- end }}
  preStartCommands:
    - {{ printf "%supdate-ca-certificates" (ternary "sudo " "" $machine.useSudo) | quote }}
  {{- end }}
  {{- if and $machine.k0s $machine.k0s.args }}
  args:
    - --kubelet-extra-args="--fail-cgroupv1=false"
    {{- toYaml $machine.k0s.args | nindent 4 }}
  {{- end }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: RemoteMachine
metadata:
  name: {{ $name }}
spec:
  address: {{ $machine.address }}
  {{- if $machine.port }}
  port: {{ $machine.port }}
  {{- end }}
  {{- if $machine.user }}
  user: {{ $machine.user }}
  {{- end }}
  {{- if $machine.useSudo }}
  useSudo: {{ $machine.useSudo }}
  {{- end }}
  {{- with $machine.provisionJob }}
  provisionJob:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  sshKeyRef:
    name: {{ $.Values.clusterIdentity.name }}
---
{{- end }}
