{{- $global := .Values.global | default dict }}
{{- $version := .Chart.AppVersion }}
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: IPAMProvider
metadata:
  name: infoblox
spec:
  version: {{ $version }}
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  {{- if $global.registry }}
  fetchConfig:
    oci: {{ $global.registry }}/capi/cluster-api-ipam-infoblox-components:{{ $version }}
  deployment:
    containers:
      - name: manager
        imageUrl: {{ $global.registry }}/capi/cluster-api-ipam-provider-infoblox:{{ $version }}
    {{- if $global.imagePullSecrets }}
    imagePullSecrets: {{ toYaml $global.imagePullSecrets | nindent 6 }}
    {{- end }}
  {{- else }}
  fetchConfig:
    url: https://github.com/telekom/cluster-api-ipam-provider-infoblox/releases/download/{{ $version }}/ipam-components.yaml
  {{- end }}
