{{- $global := .Values.global | default dict }}
{{- $version := "v1.19.4" }}
{{- $asoVersion := "v2.11.0" }}
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: azure
spec:
  version: {{ $version }}
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  manager: {{- toYaml .Values.manager | nindent 4 }}
  {{- if $global.registry }}
  fetchConfig:
    oci: {{ $global.registry }}/capi/cluster-api-provider-azure-components:{{ $version }}
  deployment:
    containers:
      - name: manager
        imageUrl: {{ $global.registry }}/capi/cluster-api-azure-controller:{{ $version }}
  {{- end }}
  manifestPatches:
    - |
      apiVersion: v1
      kind: Service
      metadata:
        name: azureserviceoperator-webhook-service
      spec:
        selector:
          control-plane: aso-controller-manager
    - |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: azureserviceoperator-controller-manager
      spec:
        selector:
          matchLabels:
            control-plane: aso-controller-manager
        template:
          metadata:
            labels:
              control-plane: aso-controller-manager
          spec:
            {{- if $global.registry }}
            containers:
            - args:
              - --metrics-addr=0.0.0.0:8443
              - --secure-metrics=true
              - --profiling-metrics=false
              - --health-addr=:8081
              - --enable-leader-election
              - --v=2
              - --crd-pattern=
              - --webhook-port=9443
              - --webhook-cert-dir=/tmp/k8s-webhook-server/serving-certs
              env:
              - name: AZURE_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    key: AZURE_CLIENT_ID
                    name: aso-controller-settings
              - name: AZURE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    key: AZURE_CLIENT_SECRET
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_TENANT_ID
                valueFrom:
                  secretKeyRef:
                    key: AZURE_TENANT_ID
                    name: aso-controller-settings
              - name: AZURE_SUBSCRIPTION_ID
                valueFrom:
                  secretKeyRef:
                    key: AZURE_SUBSCRIPTION_ID
                    name: aso-controller-settings
              - name: AZURE_CLIENT_CERTIFICATE
                valueFrom:
                  secretKeyRef:
                    key: AZURE_CLIENT_CERTIFICATE
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_CLIENT_CERTIFICATE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: AZURE_CLIENT_CERTIFICATE_PASSWORD
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_AUTHORITY_HOST
                valueFrom:
                  secretKeyRef:
                    key: AZURE_AUTHORITY_HOST
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_RESOURCE_MANAGER_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    key: AZURE_RESOURCE_MANAGER_ENDPOINT
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_RESOURCE_MANAGER_AUDIENCE
                valueFrom:
                  secretKeyRef:
                    key: AZURE_RESOURCE_MANAGER_AUDIENCE
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_TARGET_NAMESPACES
                valueFrom:
                  secretKeyRef:
                    key: AZURE_TARGET_NAMESPACES
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_OPERATOR_MODE
                valueFrom:
                  secretKeyRef:
                    key: AZURE_OPERATOR_MODE
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_SYNC_PERIOD
                valueFrom:
                  secretKeyRef:
                    key: AZURE_SYNC_PERIOD
                    name: aso-controller-settings
                    optional: true
              - name: USE_WORKLOAD_IDENTITY_AUTH
                valueFrom:
                  secretKeyRef:
                    key: USE_WORKLOAD_IDENTITY_AUTH
                    name: aso-controller-settings
                    optional: true
              - name: AZURE_USER_AGENT_SUFFIX
                valueFrom:
                  secretKeyRef:
                    key: AZURE_USER_AGENT_SUFFIX
                    name: aso-controller-settings
                    optional: true
              - name: MAX_CONCURRENT_RECONCILES
                valueFrom:
                  secretKeyRef:
                    key: MAX_CONCURRENT_RECONCILES
                    name: aso-controller-settings
                    optional: true
              - name: RATE_LIMIT_MODE
                valueFrom:
                  secretKeyRef:
                    key: RATE_LIMIT_MODE
                    name: aso-controller-settings
                    optional: true
              - name: RATE_LIMIT_QPS
                valueFrom:
                  secretKeyRef:
                    key: RATE_LIMIT_QPS
                    name: aso-controller-settings
                    optional: true
              - name: RATE_LIMIT_BUCKET_SIZE
                valueFrom:
                  secretKeyRef:
                    key: RATE_LIMIT_BUCKET_SIZE
                    name: aso-controller-settings
                    optional: true
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              image: {{ $global.registry }}/k8s/azureserviceoperator:{{ $asoVersion }}
              imagePullPolicy: Always
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: 8081
                initialDelaySeconds: 60
              name: manager
              ports:
              - containerPort: 9443
                name: webhook-server
                protocol: TCP
              - containerPort: 8081
                name: health-port
                protocol: TCP
              - containerPort: 8443
                name: metrics-port
                protocol: TCP
              readinessProbe:
                httpGet:
                  path: /readyz
                  port: 8081
                initialDelaySeconds: 60
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 200m
                  memory: 256Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 65532
                runAsNonRoot: true
                runAsUser: 65532
              volumeMounts:
              - mountPath: /var/run/secrets/tokens
                name: azure-identity
                readOnly: true
              - mountPath: /tmp/k8s-webhook-server/serving-certs
                name: cert
                readOnly: true
            {{- end }}
            volumes:
            - name: cert
              secret:
                defaultMode: 420
                secretName: aso-webhook-server-cert
            - name: azure-identity
              projected:
                defaultMode: 420
                sources:
                - serviceAccountToken:
                    audience: api://AzureADTokenExchange
                    expirationSeconds: 3600
                    path: azure-identity
    - |
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: azureserviceoperator-serving-cert
      spec:
        secretName: aso-webhook-server-cert
