apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-docker-1-0-7
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-docker
      version: 1.0.7
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
