apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-k0sproject-k0smotron-1-0-1
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-k0sproject-k0smotron
      version: 1.0.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
