apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-azure-1-0-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-azure
      version: 1.0.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
