apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: docker-hosted-cp-1-0-4
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: docker-hosted-cp
      version: 1.0.4
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
