apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: openstack-hosted-cp-1-0-6
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: openstack-hosted-cp
      version: 1.0.6
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
