apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: projectsveltos-0-51-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: projectsveltos
      version: 0.51.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
