apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: remote-cluster-1-0-16
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: remote-cluster
      version: 1.0.16
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: kcm-templates
