apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  version: {{ .Values.k0s.version | replace "+" "-" }}
  persistence:
    type: emptyDir
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.k0smotron.controllerPlaneFlags }}
  controllerPlaneFlags: {{ toYaml . | nindent 4 }}
  {{- end }}
