apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  version: {{ .Values.k0s.version | replace "+" "-"  | quote }}
  persistence:
    type: emptyDir
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.encryption.configSecret.name .Values.audit.policyRef.name }}
  mounts:
    {{- if .Values.encryption.configSecret.name }}
    - path: {{ include "encryption-config.dir" . }}
      secret:
        defaultMode: 420
        items:
          - key: {{ default "config" .Values.encryption.configSecret.key  | quote }}
            path: {{ include "encryption-config.file" . }}
        secretName: {{ .Values.encryption.configSecret.name  | quote }}
    {{- end }}
    {{- if .Values.audit.policyRef.name }}
    - path: {{ include "audit-policy.dir" . }}
      configMap:
        defaultMode: 420
        items:
          - key: {{ .Values.audit.policyRef.key  | quote }}
            path: {{ include "audit-policy.file" . }}
        name: {{ .Values.audit.policyRef.name  | quote }}
    {{- end }}
  {{- end }}
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      api:
        extraArgs:
          {{- if .Values.encryption.configSecret.name }}
          encryption-provider-config: {{ include "encryption-config.fullpath" . }}
          {{- if .Values.encryption.automaticReload }}
          encryption-provider-config-automatic-reload: "true"
          {{- end }}
          {{- end }}
          {{- if .Values.audit.policyRef.name }}
          audit-policy-file: {{ include "audit-policy.fullpath" . }}
          audit-log-path: "-"
          {{- end }}
  {{- with .Values.k0smotron.controllerPlaneFlags }}
  controllerPlaneFlags: {{ toYaml . | nindent 4 }}
  {{- end }}
