{{- $global := .Values.global | default dict }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlane
metadata:
  name: {{ include "k0scontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version }}
  k0sConfigSpec:
    {{- if $global.k0sURL }}
    downloadURL: "{{ $global.k0sURL }}/k0s-{{ .Values.k0s.version }}-{{ .Values.k0s.arch }}"
    {{- end }}
    files:
      - path: /home/{{ .Values.controlPlane.ssh.user }}/.ssh/authorized_keys
        permissions: "0600"
        content: "{{ trim .Values.controlPlane.ssh.publicKey }}"
      {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
      {{- $certs := dict "registry.crt" $global.registryCertSecret "k0s-url.crt" $global.k0sURLCertSecret }}
      {{- range $path, $secret := $certs }}
      {{- if $secret }}
      - contentFrom:
          secretRef:
            name: {{ $secret }}
            key: ca.crt
        permissions: "0664"
        path: /usr/local/share/ca-certificates/{{ $path }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.auth.configSecret.name }}
      - contentFrom:
          secretRef:
            name: {{ .Values.auth.configSecret.name }}
            key: {{ default "config" .Values.auth.configSecret.key }}
        permissions: "0644"
        path: {{ include "authentication-config.fullpath" . }}
      {{- end }}
    preStartCommands:
      - chown {{ .Values.controlPlane.ssh.user }} /home/{{ .Values.controlPlane.ssh.user }}/.ssh/authorized_keys
      - sed -i 's/"externalAddress":"{{ .Values.controlPlaneEndpointIP }}",//' /etc/k0s.yaml
      {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
      - "sudo update-ca-certificates"
      {{- end }}
    args:
      - --enable-worker
      - --disable-components=konnectivity-server
      {{- range $arg := .Values.k0s.cpArgs }}
      - {{ toYaml $arg }}
      {{- end }}
    k0s:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          sans:
            - {{ .Values.controlPlaneEndpointIP }}
          extraArgs:
            {{- if not .Values.auth.configWithAnon }}
            anonymous-auth: "true"
            {{- end }}
            {{- if .Values.auth.configSecret.name }}
            authentication-config: {{ include "authentication-config.fullpath" . }}
            {{- end }}
            {{- with .Values.k0s.api.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.k0s.network }}
        network: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if $global.registry }}
        images:
          repository: "{{ $global.registry }}"
        {{- end }}
        extensions:
          helm:
            {{- if not $global.registry }}
            repositories:
            - name: kube-vip
              url: https://kube-vip.github.io/helm-charts
            - name: vsphere-cpi
              url: https://kubernetes.github.io/cloud-provider-vsphere
            - name: mirantis
              url: https://charts.mirantis.com
            {{- end }}
            charts:
            - name: kube-vip
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/charts/kube-vip
              {{- else }}
              chartname: kube-vip/kube-vip
              {{- end }}
              version: 0.6.1
              order: 1
              namespace: kube-system
              values: |
                {{- if $global.registry }}
                image:
                  repository: {{ $global.registry }}/kube-vip/kube-vip
                {{- end }}
                config:
                  address: {{ .Values.controlPlaneEndpointIP }}
                env:
                  svc_enable: "true"
                  cp_enable: "true"
                  lb_enable: "false"
                nodeSelector:
                  node-role.kubernetes.io/control-plane: "true"
                tolerations:
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/master
                    operator: Exists
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - effect: NoSchedule
                    key: node.cloudprovider.kubernetes.io/uninitialized
                    value: "true"
            - name: vsphere-cpi
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/charts/vsphere-cpi
              {{- else }}
              chartname: vsphere-cpi/vsphere-cpi
              {{- end }}
              version: 1.31.0
              order: 2
              namespace: kube-system
              values: |
                config:
                  enabled: false
                daemonset:
                  {{- if $global.registry }}
                  image: {{ $global.registry }}/cloud-pv-vsphere/cloud-provider-vsphere
                  {{- end }}
                  tolerations:
                    - effect: NoSchedule
                      key: node.cloudprovider.kubernetes.io/uninitialized
                      value: "true"
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/master
                      operator: Exists
                    - effect: NoSchedule
                      key: node-role.kubernetes.io/control-plane
                      operator: Exists
                    - effect: NoSchedule
                      key: node.kubernetes.io/not-ready
                      operator: Exists
                    - key: CriticalAddonsOnly
                      effect: NoExecute
                      operator: Exists
            - name: vsphere-csi-driver
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/charts/vsphere-csi-driver
              {{- else }}
              chartname: mirantis/vsphere-csi-driver
              {{- end }}
              version: 0.0.3
              order: 3
              namespace: kube-system
              values: |
                vcenterConfig:
                  enabled: false
                node:
                  kubeletPath: /var/lib/k0s/kubelet
                defaultStorageClass:
                  enabled: true
                images:
                  driver:
                    {{- if $global.registry }}
                    repo: {{ $global.registry }}/csi-vsphere/driver
                    {{- end }}
                    tag: v3.1.2
                  syncer:
                    {{- if $global.registry }}
                    repo: {{ $global.registry }}/csi-vsphere/syncer
                    {{- end }}
                    tag: v3.1.2
                  {{- if $global.registry }}
                  nodeDriverRegistrar:
                    repo: {{ $global.registry }}/sig-storage/csi-node-driver-registrar
                  csiAttacher:
                    repo: {{ $global.registry }}/sig-storage/csi-attacher
                  csiResizer:
                    repo: {{ $global.registry }}/sig-storage/csi-resizer
                  csiProvisioner:
                    repo: {{ $global.registry }}/sig-storage/csi-provisioner
                  csiSnapshotter:
                    repo: {{ $global.registry }}/sig-storage/csi-snapshotter
                  livenessProbe:
                    repo: {{ $global.registry }}/sig-storage/livenessprobe
                  {{- end }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VSphereMachineTemplate
      name: {{ include "vspheremachinetemplate.controlplane.name" . }}
      namespace: {{ .Release.Namespace }}
