{{- if not .Values.enableAutopilot }}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedMachinePool
metadata:
  name: {{ include "machinepool.name" . }}
spec:
  nodePoolName: {{ .Values.machines.nodePoolName  | quote }}
  machineType: {{ .Values.machines.machineType  | quote }}
  diskSizeGB: {{ .Values.machines.diskSizeGB }}
  {{- with .Values.machines }}
  localSsdCount: {{ .localSsdCount }}
  # See: https://github.com/k0rdent/kcm/issues/2034
  # Omit locationPolicy if empty is set.
  # Empty value is allowed to survive k8s CRD JSON (de)serializations and null pruning.
  {{- with .scaling }}
  {{- $scaling := . }}
  {{- if and (hasKey . "locationPolicy") (eq (get . "locationPolicy") "") }}
  {{- $scaling = omit . "locationPolicy" }}
  {{- end }}
  scaling: {{- toYaml $scaling | nindent 4 }}
  {{- end }}
  {{- with .nodeLocations }}
  nodeLocations: {{- toYaml . | nindent 4 }}
  {{- end }}
  imageType: {{ .imageType }}
  instanceType: {{ .instanceType }}
  diskType: {{ .diskType }}
  maxPodsPerNode: {{ .maxPodsPerNode }}
  {{- with .kubernetesLabels }}
  kubernetesLabels: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .kubernetesTaints }}
  kubernetesTaints: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .additionalLabels }}
  additionalLabels: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .management }}
  management: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
