apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
spec:
  version: v1.9.6
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
  manager: {{- toYaml .Values.manager | nindent 4 }}
