apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ include "awsmachinetemplate.worker.name" . }}
spec:
  template:
    spec:
      {{- $ami := default dict .Values.worker.ami }}
      ami:
        {{- if $ami.id }}
        id: {{ $ami.id }}
        {{- else if .Values.worker.amiID }}
        id: {{ .Values.worker.amiID }}
        {{- else }}
        eksLookupType: {{ default "AmazonLinux2023" $ami.eksLookupType }}
        {{- end }}
      {{- with .Values.worker.cloudInit }}
      cloudInit: {{- toYaml . | nindent 8 }}
      {{- end }}
      imageLookupFormat: {{ .Values.worker.imageLookup.format }}
      imageLookupOrg: {{ .Values.worker.imageLookup.org }}
      imageLookupBaseOS: {{ .Values.worker.imageLookup.baseOS }}
      instanceType: {{ .Values.worker.instanceType }}
      iamInstanceProfile: {{ .Values.worker.iamInstanceProfile }}
      publicIP: {{ .Values.publicIP }}
      rootVolume:
        size: {{ .Values.worker.rootVolumeSize }}
      {{- with .Values.worker.nonRootVolumes }}
      nonRootVolumes: {{- toYaml . | nindent 8 }}
      {{- end }}
      uncompressedUserData: {{ .Values.worker.uncompressedUserData }}
      {{- if not (quote .Values.sshKeyName | empty) }}
      sshKeyName: {{ .Values.sshKeyName | quote }}
      {{- end }}
