apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: {{ include "awsmanagedcontrolplane.name" . }}
spec:
  eksClusterName: {{ .Values.eksClusterName  | quote }}
  region: {{ .Values.region  | quote }}
  {{- $sshKeyName := .Values.sshKeyName }}
  {{- if ne $sshKeyName nil }}
  sshKeyName: {{ $sshKeyName | quote }}
  {{- end }}
  version: {{ .Values.kubernetes.version  | quote }}
  associateOIDCProvider: {{ .Values.associateOIDCProvider }}
  {{- with .Values.oidcIdentityProviderConfig }}
  oidcIdentityProviderConfig: {{- toYaml . | nindent 4 }}
  {{- end }}
  vpcCni:
    disable: {{ .Values.vpcCni.disable }}
    {{- if .Values.vpcCni.env }}
    env: {{- toYaml .Values.vpcCni.env | nindent 4}}
    {{- end }}
  kubeProxy:
    disable: {{ .Values.kubeProxy.disable }}
  identityRef:
    kind: {{ .Values.clusterIdentity.kind  | quote }}
    name: {{ .Values.clusterIdentity.name  | quote }}
  {{- with .Values.addons }}
  addons: {{- toYaml . | nindent 4 }}
  {{- end }}
