apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}
  {{- if .Values.clusterLabels }}
  labels: {{- toYaml .Values.clusterLabels | nindent 4}}
  {{- end }}
  {{- if .Values.clusterAnnotations }}
  annotations: {{- toYaml .Values.clusterAnnotations | nindent 4}}
  {{- end }}
spec:
  {{- with .Values.clusterNetwork }}
  clusterNetwork:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: AWSManagedControlPlane
    name: {{ include "awsmanagedcontrolplane.name" .  }}
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: AWSManagedCluster
    name: {{ include "cluster.name" . }}
