{{- $global := .Values.global | default dict }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: K0sControlPlane
metadata:
  name: {{ include "k0scontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version  | quote }}
  k0sConfigSpec:
    {{- if $global.k0sURL }}
    downloadURL: "{{ $global.k0sURL }}/k0s-{{ .Values.k0s.version }}-{{ .Values.k0s.arch }}"
    {{- end }}
    {{- if or $global.registryCertSecret $global.k0sURLCertSecret .Values.auth.configSecret.name .Values.encryption.configSecret.name $global.registryCredentialSecret .Values.audit.policyRef.name }}
    {{- $certs := dict "registry.crt" $global.registryCertSecret "k0s-url.crt" $global.k0sURLCertSecret }}
    files:
      {{- range $path, $secret := $certs }}
      {{- if $secret }}
      - contentFrom:
          secretRef:
            name: {{ $secret }}
            key: ca.crt
        permissions: "0664"
        path: /usr/local/share/ca-certificates/{{ $path }}
      {{- end }}
      {{- end }}
      {{- if .Values.auth.configSecret.name }}
      - contentFrom:
          secretRef:
            name: {{ .Values.auth.configSecret.name  | quote }}
            key: {{ default "config" .Values.auth.configSecret.key  | quote }}
        permissions: "0644"
        path: {{ include "authentication-config.fullpath" . }}
      {{- end }}
      {{- if .Values.encryption.configSecret.name }}
      - contentFrom:
          secretRef:
            name: {{ .Values.encryption.configSecret.name  | quote }}
            key: {{ default "config" .Values.encryption.configSecret.key  | quote }}
        permissions: "0644"
        path: {{ include "encryption-config.fullpath" . }}
      {{- end }}
      {{- if .Values.audit.policyRef.name }}
      - contentFrom:
          configMapRef:
            name: {{ .Values.audit.policyRef.name  | quote }}
            key: {{ default "policy" .Values.audit.policyRef.key  | quote }}
        permissions: "0644"
        path: {{ include "audit-policy.fullpath" . }}
      {{- end }}
      {{- if $global.registryCredentialSecret }}
      - contentFrom:
          secretRef:
            name: {{ $global.registryCredentialSecret }}
            key: registryCredential
        permissions: "0644"
        path: /var/lib/k0s/manifests/kcm/helm-registry-credentials.yaml
      - contentFrom:
          secretRef:
            name: {{ $global.registryCredentialSecret }}
            key: containerdAuth
        permissions: "0664"
        path: /etc/k0s/containerd.d/registry-auth.toml
      {{- end }}
    {{- end }}
    {{- if or $global.registryCertSecret $global.k0sURLCertSecret }}
    preK0sCommands:
    - "sudo update-ca-certificates"
    {{- end }}
    {{- if and .Values.audit.policyRef.name .Values.audit.logPath (ne .Values.audit.logPath "-") }}
    {{- $logPath := .Values.audit.logPath }}
    {{- $logDir := dir $logPath }}
    postK0sCommands:
    - 'sudo mkdir -p {{ $logDir }}'
    - 'sudo chown kube-apiserver:kube-apiserver {{ $logDir }}'
    {{- end }}
    args:
      - --enable-worker
      {{- if eq (int .Values.workersNumber) 0 }}
      - --no-taints
      {{- end }}
      - --disable-components=konnectivity-server
      - --kubelet-extra-args="--fail-cgroupv1=false"
      {{- range $arg := .Values.k0s.cpArgs }}
      - {{ toYaml $arg }}
      {{- end }}
    k0s:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          extraArgs:
            {{- if not .Values.auth.configWithAnon }}
            anonymous-auth: "true"
            {{- end }}
            {{- if .Values.auth.configSecret.name }}
            authentication-config: {{ include "authentication-config.fullpath" . }}
            {{- end }}
            {{- if .Values.encryption.configSecret.name }}
            encryption-provider-config: {{ include "encryption-config.fullpath" . }}
            {{- if .Values.encryption.automaticReload }}
            encryption-provider-config-automatic-reload: "true"
            {{- end }}
            {{- end }}
            {{- if .Values.audit.policyRef.name }}
            audit-policy-file: {{ include "audit-policy.fullpath" . }}
            {{- with .Values.audit.logPath }}
            audit-log-path: {{ . | quote }}
            {{- end }}
            {{- if and .Values.audit.logPath (ne .Values.audit.logPath "-") }}
            {{- with .Values.audit.logMaxAge }}
            audit-log-maxage: {{ . | quote }}
            {{- end }}
            {{- with .Values.audit.logMaxBackup }}
            audit-log-maxbackup: {{ . | quote }}
            {{- end }}
            {{- with .Values.audit.logMaxSize }}
            audit-log-maxsize: {{ . | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- with .Values.k0s.api.extraArgs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.k0s.network }}
        network: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if $global.registry }}
        images:
          repository: "{{ $global.registry }}"
        {{- end }}
        extensions:
          helm:
            {{- with .Values.k0s.extensions.helm.repositories }}
            repositories:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.k0s.extensions.helm.charts }}
            charts:
              {{- toYaml . | nindent 12 }}
            {{- end }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtMachineTemplate
      name: {{ include "kubevirtmachinetemplate.controlplane.name" . }}
      namespace: {{ .Release.Namespace }}
