apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: {{ include "awsmachinetemplate.controlplane.name" . }}
spec:
  template:
    spec:
      {{- $amiID := .Values.controlPlane.amiID | default "" | trim }}
      {{- if $amiID }}
      ami:
        id: {{ $amiID | quote }}
      {{- else }}
      imageLookupFormat: {{ .Values.controlPlane.imageLookup.format | quote }}
      imageLookupOrg: {{ .Values.controlPlane.imageLookup.org | quote }}
      imageLookupBaseOS: {{ .Values.controlPlane.imageLookup.baseOS | quote }}
      {{- end }}
      instanceType: {{ .Values.controlPlane.instanceType  | quote }}
      # Instance Profile created by `clusterawsadm bootstrap iam create-cloudformation-stack`
      iamInstanceProfile: {{ .Values.controlPlane.iamInstanceProfile  | quote }}
      cloudInit:
        # Makes CAPA use k0s bootstrap cloud-init directly and not via SSM
        # Simplifies the VPC setup as we do not need custom SSM endpoints etc.
        insecureSkipSecretsManager: true
      publicIP: {{ .Values.publicIP }}
      rootVolume:
        size: {{ .Values.controlPlane.rootVolumeSize }}
      {{- with .Values.controlPlane.nonRootVolumes }}
      nonRootVolumes: {{- toYaml . | nindent 8 }}
      {{- end }}
      uncompressedUserData: {{ .Values.controlPlane.uncompressedUserData }}
