apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-clusters-viewer-role
  labels:
    k0rdent.mirantis.com/aggregate-to-namespace-viewer: "true"
rules:
  - apiGroups:
      - k0rdent.mirantis.com
    resources:
      - clusterdeployments
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
