apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-namespace-viewer-role
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        k0rdent.mirantis.com/aggregate-to-namespace-viewer: "true"
