name: Check Providers in Config
description: Detect on-prem, cloud, and optional custom provider presence

inputs:
  config:
    description: Base64-encoded config (YAML)
    required: false
  provider:
    description: Optional provider name to check for presence
    required: false

outputs:
  provider_present:
    description: Whether the given provider is present (if provided)
    value: ${{ steps.eval.outputs.provider_present }}
  onprem_present:
    description: Whether any on-prem provider (vsphere/openstack) is present
    value: ${{ steps.eval.outputs.onprem_present }}
  cloud_present:
    description: Whether any cloud provider (not on-prem) is present
    value: ${{ steps.eval.outputs.cloud_present }}

runs:
  using: "composite"
  steps:
    - name: Decode and evaluate config
      id: eval
      shell: bash
      run: |
        echo "provider_present=false" >> "$GITHUB_OUTPUT"
        echo "onprem_present=false" >> "$GITHUB_OUTPUT"
        echo "cloud_present=false" >> "$GITHUB_OUTPUT"

        if [ -z "${{ inputs.config }}" ]; then
          echo "No config provided — fallback to aws"
          echo "aws: []" > config.yaml
        else
          echo "${{ inputs.config }}" | base64 -d > config.yaml
        fi

        # Set of on-prem providers (hardcoded)
        ONPREM_PROVIDERS=("vsphere" "openstack")

        # Initialize flags
        found_onprem=false
        found_cloud=false

        # Check for given provider
        if [ -n "${{ inputs.provider }}" ]; then
          echo "Checking for provider: '${{ inputs.provider }}'"
          grep -E "^${{ inputs.provider }}:" config.yaml > /dev/null \
            && echo "provider_present=true" >> "$GITHUB_OUTPUT" \
            || echo "provider_present=false" >> "$GITHUB_OUTPUT"
        fi

        # Loop through top-level keys
        while IFS= read -r line; do
          key=$(echo "$line" | cut -d':' -f1 | xargs)

          if [[ -z "$key" ]]; then
            continue
          fi

          if [[ " ${ONPREM_PROVIDERS[*]} " =~ " $key " ]]; then
            echo "Detected on-prem provider: $key"
            found_onprem=true
          else
            echo "Detected cloud provider: $key"
            found_cloud=true
          fi
        done < <(grep '^[a-zA-Z0-9_]\+:' config.yaml)

        echo "onprem_present=$found_onprem" >> "$GITHUB_OUTPUT"
        echo "cloud_present=$found_cloud" >> "$GITHUB_OUTPUT"

        rm config.yaml
