apiVersion: k0rdent.mirantis.com/v1beta1
kind: Release
metadata:
  name: kcm-1-6-0
  annotations:
    helm.sh/resource-policy: keep
spec:
  version: 1.6.0
  kcm:
    template: kcm-1-6-0
  regional:
    template: kcm-regional-1-6-0
  capi:
    template: cluster-api-1-1-2
  providers:
    - name: cluster-api-provider-k0sproject-k0smotron
      template: cluster-api-provider-k0sproject-k0smotron-1-0-16
    - name: cluster-api-provider-azure
      template: cluster-api-provider-azure-1-0-14
    - name: cluster-api-provider-vsphere
      template: cluster-api-provider-vsphere-1-0-10
    - name: cluster-api-provider-aws
      template: cluster-api-provider-aws-1-0-12
    - name: cluster-api-provider-openstack
      template: cluster-api-provider-openstack-1-0-15
    - name: cluster-api-provider-docker
      template: cluster-api-provider-docker-1-0-9
    - name: cluster-api-provider-gcp
      template: cluster-api-provider-gcp-1-0-9
    - name: cluster-api-provider-ipam
      template: cluster-api-provider-ipam-1-0-6
    - name: cluster-api-provider-infoblox
      template: cluster-api-provider-infoblox-1-0-5
    - name: cluster-api-provider-kubevirt
      template: cluster-api-provider-kubevirt-1-0-0
    - name: projectsveltos
      template: projectsveltos-1-1-1
