apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: {{ include "vspheremachinetemplate.name" . }}
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: {{ .Values.vsphere.datacenter  | quote }}
      datastore: {{ .Values.vsphere.datastore  | quote }}
      diskGiB: {{ .Values.rootVolumeSize }}
      folder: {{ .Values.vsphere.folder  | quote }}
      memoryMiB: {{ .Values.memory }}
      network:
        devices:
        - dhcp4: true
          networkName: {{ .Values.network  | quote }}
      numCPUs: {{ .Values.cpus }}
      os: Linux
      powerOffMode: hard
      resourcePool: {{ .Values.vsphere.resourcePool  | quote }}
      server: {{ .Values.vsphere.server  | quote }}
      storagePolicyName: ""
      template: {{ .Values.vmTemplate  | quote }}
      thumbprint: {{ .Values.vsphere.thumbprint  | quote }}
