apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: {{ include "cluster.name" . }}
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron
    aws.cluster.x-k8s.io/external-resource-gc: "true"
  finalizers:
  - k0rdent.mirantis.com/cleanup
spec:
  region: {{ .Values.region  | quote }}
  identityRef:
    kind: {{ .Values.clusterIdentity.kind  | quote }}
    name: {{ .Values.clusterIdentity.name  | quote }}
  network:
    vpc:
      id: {{ .Values.vpcID  | quote }}
    {{- with .Values.subnets }}
    subnets:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- $sshKeyName := .Values.sshKeyName }}
  {{- if ne $sshKeyName nil }}
  sshKeyName: {{ $sshKeyName | quote }}
  {{- end }}
  {{- with .Values.bastion }}
  bastion:
    {{- toYaml . | nindent 4 }}
  {{- end }}
