{{- $global := .Values.global | default dict }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $global.registry }}
  image: {{ $global.registry }}/k0sproject/k0s
  etcd:
    image: "{{ $global.registry }}/k0sproject/etcd:v3.5.13"
  {{- end }}
  {{- if or $global.registryCertSecret .Values.auth.configSecret.name .Values.dataSource.caSecret.name }}
  mounts:
    {{- if $global.registryCertSecret }}
    - path: /usr/local/share/ca-certificates/registry
      secret:
        defaultMode: 420
        items:
          - key: ca.crt
            path: ca.crt
        secretName: {{ $global.registryCertSecret }}
    {{- end }}
    {{- if .Values.auth.configSecret.name }}
    - path: {{ include "authentication-config.dir" . }}
      secret:
        defaultMode: 420
        items:
          - key: {{ .Values.auth.configSecret.key }}
            path: {{ include "authentication-config.file" . }}
        secretName: {{ .Values.auth.configSecret.name }}
    {{- end }}
    {{- if .Values.dataSource.caSecret.name }}
    - path: /var/lib/k0s/kine-ca
      secret:
        defaultMode: 420
        items:
          - key: {{ .Values.dataSource.caSecret.key }}
            path: ca.crt
        secretName: {{ .Values.dataSource.caSecret.name }}
    {{- end }}
  {{- end }}
  {{- if .Values.dataSource.kineDataSourceSecretName }}
  kineDataSourceSecretName: {{ .Values.dataSource.kineDataSourceSecretName }}
  {{- end }}
  controllerPlaneFlags:
    - --enable-cloud-provider=true
    - --debug=true
    {{- range $arg := .Values.k0smotron.controllerPlaneFlags }}
    - {{ toYaml $arg }}
    {{- end }}
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      api:
        extraArgs:
          {{- if .Values.auth.configSecret.name }}
          authentication-config: {{ include "authentication-config.fullpath" . }}
          {{- end }}
          {{- with .Values.k0s.api.extraArgs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.k0s.network }}
      network: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if $global.registry }}
      images:
        repository: "{{ $global.registry }}"
      {{- end }}
      extensions:
        helm:
          repositories:
          {{- if not $global.registry }}
            - name: mirantis
              url: https://charts.mirantis.com
          {{- else }}
            - name: global-registry
              url: oci://{{ regexReplaceAll "/.*" $global.registry "" }}
              {{- if $global.registryCertSecret }}
              caFile: /usr/local/share/ca-certificates/registry/ca.crt
              {{- end }}
          {{- end }}
          charts:
            - name: gcp-cloud-controller-manager
              namespace: kube-system
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/charts/gcp-cloud-controller-manager
              {{- else }}
              chartname: mirantis/gcp-cloud-controller-manager
              {{- end }}
              version: "0.0.1"
              values: |
                cloudConfig:
                  enabled: true
                  data: W0dsb2JhbF0KbXVsdGl6b25lPXRydWUK
                cloudCredentials:
                  secretName: gcp-cloud-sa
                  secretKey: cloud-sa.json
                clusterCIDR: {{ first .Values.clusterNetwork.pods.cidrBlocks }}
                image:
                  {{- if $global.registry }}
                  repository: {{ $global.registry }}/k8s-staging-cloud-provider-gcp/cloud-controller-manager
                  {{- end }}
                  tag: v32.2.3
                args:
                  - --cloud-provider=gce
                  - --leader-elect=true
                  - --use-service-account-credentials=true
                  - --allocate-node-cidrs=true
                  - --configure-cloud-routes=false
                  - --v=2
            - name: gcp-compute-persistent-disk-csi-driver
              namespace: kube-system
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/charts/gcp-compute-persistent-disk-csi-driver
              {{- else }}
              chartname: mirantis/gcp-compute-persistent-disk-csi-driver
              {{- end }}
              version: "0.0.2"
              values: |
                cloudCredentials:
                  secretName: gcp-cloud-sa
                  secretKey: cloud-sa.json
                node:
                  linux:
                    enabled: true
                    kubeletPath: /var/lib/k0s/kubelet
                    {{- if $global.registry }}
                    registrar:
                      image:
                        repository: {{ $global.registry }}/sig-storage/csi-node-driver-registrar
                    driver:
                      image:
                        repository: {{ $global.registry }}/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver
                    {{- end }}
                  windows:
                    enabled: false
                defaultStorageClass:
                  enabled: true
                  {{- if $global.registry }}
                controller:
                  provisioner:
                    image:
                      repository: {{ $global.registry }}/sig-storage/csi-provisioner
                  attacher:
                    image:
                      repository: {{ $global.registry }}/sig-storage/csi-attacher
                  resizer:
                    image:
                      repository: {{ $global.registry }}/sig-storage/csi-resizer
                  snapshotter:
                    image:
                      repository: {{ $global.registry }}/sig-storage/csi-snapshotter
                  driver:
                    image:
                      repository: {{ $global.registry }}/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver
                {{- end }}
