// Copyright 2026
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1beta1

import (
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterRoleBindingNamePrefix is prepended to a binding's Name to produce the name of the
// ClusterRoleBinding materialized for it in the child cluster (see RBACPolicyBinding.Name).
const ClusterRoleBindingNamePrefix = "k0rdent-"

// RBACPolicySubject names one ClusterRoleBinding subject.
//
// RBACPolicy makes no assumption about how (or whether) the child cluster's authentication is
// configured: Name is written verbatim by the author to match whatever that specific setup
// actually asserts (a ClusterAuthentication's JWT claim mapping, some other identity provider, or
// none at all) — for example "k0rdent:project:project-2:compute-admin".
type RBACPolicySubject struct {
	// +required
	// +kubebuilder:validation:Enum=User;Group

	// kind is the Kubernetes RBAC subject kind: "User" or "Group".
	Kind string `json:"kind,omitempty"`

	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=256

	// name is the exact subject name (see the RBACPolicySubject doc comment).
	Name string `json:"name,omitempty"`
}

// RBACPolicyBinding maps a single Kubernetes ClusterRole to the exact set of ClusterRoleBinding
// subjects that should be bound to it in the targeted child cluster.
type RBACPolicyBinding struct {
	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=245

	// name identifies this binding within the policy (for example "compute-admin"). It is used to
	// name the generated ClusterRoleBinding ("k0rdent-<name>").
	Name string `json:"name,omitempty"`

	// +required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253

	// clusterRole is the name of the Kubernetes ClusterRole that Name is bound to in the child
	// cluster. It may be a built-in ClusterRole (e.g. "admin", "edit", "view") or a custom one,
	// either already present in the child cluster or defined inline via Rules.
	ClusterRole string `json:"clusterRole,omitempty"`

	// +optional
	// +listType=atomic
	// +kubebuilder:validation:MaxItems=1024

	// rules optionally supplies the PolicyRules for the ClusterRole named by ClusterRole, for the case
	// where that ClusterRole does not already exist in the child cluster (e.g. a custom role). When
	// set, the operator creates/updates that ClusterRole (with these rules) alongside the
	// ClusterRoleBinding. Leave unset to bind to a ClusterRole that is expected to already exist
	// (e.g. a built-in role) — the operator never modifies a ClusterRole it did not create.
	Rules []rbacv1.PolicyRule `json:"rules,omitempty"`

	// +required
	// +listType=atomic
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=1024

	// subjects is the ClusterRoleBinding subject list for this binding. See RBACPolicySubject.
	Subjects []RBACPolicySubject `json:"subjects,omitempty"`
}

// RBACPolicySpec defines the role catalog: a set of ClusterRole -> subjects bindings that the RBAC
// operator reconciles into the child cluster of every [ClusterDeployment] that references this
// RBACPolicy via spec.rbacPolicy.
type RBACPolicySpec struct {
	// +required
	// +listType=map
	// +listMapKey=name
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=200

	// bindings is the role catalog: each entry maps one ClusterRole to a set of subjects,
	// materialized as a ClusterRoleBinding in the child cluster of each referencing ClusterDeployment.
	Bindings []RBACPolicyBinding `json:"bindings,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:scope=Namespaced,shortName=rbacpol

// RBACPolicy is the Schema for the rbacpolicies API.
//
// It is a role catalog: any number of [ClusterDeployment] objects in the same namespace opt in by
// setting spec.rbacPolicy to its name. For each entry in spec.bindings, the RBAC operator
// creates/updates a "k0rdent-<name>" ClusterRoleBinding in each referencing ClusterDeployment's
// child cluster, using the kubeconfig generated by Cluster API.
type RBACPolicy struct {
	metav1.TypeMeta `json:",inline"`

	// +optional

	// metadata contains the object metadata
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +required

	// spec defines the desired state of the RBACPolicy
	Spec RBACPolicySpec `json:"spec,omitempty,omitzero"`
}

// +kubebuilder:object:root=true

// RBACPolicyList contains a list of RBACPolicy.
type RBACPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RBACPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RBACPolicy{}, &RBACPolicyList{})
}
