apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcm.fullname" . }}-statemanagementproviders-creator-role
  labels:
    k0rdent.mirantis.com/aggregate-to-global-admin: "true"
rules:
  - apiGroups:
      - k0rdent.mirantis.com
    resources:
      - statemanagementproviders
      - statemanagementproviders/status
    verbs: {{ include "rbac.editorVerbs" . | nindent 6 }}
