apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: {{ include "gcpmachinetemplate.controlplane.name" . }}
spec:
  template:
    spec:
      {{- with .Values.controlPlane }}
      instanceType: {{ .instanceType }}
      {{- if .subnet }}
      subnet: {{ .subnet }}
      {{- end }}
      {{- if .providerID }}
      providerID: {{ .providerID }}
      {{- end }}
      {{- if .imageFamily }}
      imageFamily: {{ .imageFamily }}
      {{- end }}
      {{- if .image }}
      image: {{ .image }}
      {{- end }}
      {{- if .additionalLabels }}
      additionalLabels: {{- toYaml .additionalLabels | nindent 8 }}
      {{- end }}
      publicIP: {{ .publicIP }}
      {{- if .additionalNetworkTags }}
      additionalNetworkTags: {{- toYaml .additionalNetworkTags | nindent 8 }}
      {{- end }}
      rootDeviceSize: {{ .rootDeviceSize }}
      rootDeviceType: {{ .rootDeviceType }}
      {{- with .serviceAccount }}
      serviceAccounts:
        email: {{ required "controlPlane.serviceAccount.email is required" .email }}
        scopes: {{- required "controlPlane.serviceAccount.scopes is required" .scopes | toYaml | nindent 10 }}
      {{- end }}
      ipForwarding: {{ .ipForwarding }}
      {{- end }}
