apiVersion: hmc.mirantis.com/v1alpha1
kind: ClusterTemplate
metadata:
  name: aws-eks-0-0-2
  annotations:
    helm.sh/resource-policy: keep
  labels:
    hmc.mirantis.com/component: hmc
spec:
  helm:
    chartName: aws-eks
    chartVersion: 0.0.2
