apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: {{ include "cluster.name" . }}
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron
  finalizers:
  - k0rdent.mirantis.com/cleanup
spec:
  {{- with .Values.clusterIdentity }}
  identityRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  networkSpec:
    vnet:
      resourceGroup: {{ .Values.resourceGroup  | quote }}
      name: {{ .Values.network.vnetName  | quote }}
    subnets:
      - name: {{ .Values.network.nodeSubnetName  | quote }}
        role: node
        routeTable:
          name: {{ .Values.network.routeTableName  | quote }}
        securityGroup:
          name: {{ .Values.network.securityGroupName  | quote }}
  location: {{ .Values.location  | quote }}
  {{- if .Values.bastion.enabled }}
  {{- with .Values.bastion.bastionSpec }}
  bastionSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  subscriptionID: {{ required ".Values.subscriptionID is required to create a cluster" .Values.subscriptionID  | quote }}
  resourceGroup: {{ .Values.resourceGroup  | quote }}
