{{- $global := .Values.global | default dict }}
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $global.registry }}
  image: {{ $global.registry }}/k0sproject/k0s
  etcd:
    image: "{{ $global.registry }}/k0sproject/etcd:v3.5.13"
  {{- end }}
  {{- if or $global.registryCertSecret .Values.auth.configSecret.name .Values.dataSource.caSecret.name }}
  mounts:
    {{- if $global.registryCertSecret }}
    - path: /usr/local/share/ca-certificates/registry
      secret:
        defaultMode: 420
        items:
          - key: ca.crt
            path: ca.crt
        secretName: {{ $global.registryCertSecret }}
    {{- end }}
    {{- if .Values.auth.configSecret.name }}
    - path: {{ include "authentication-config.dir" . }}
      secret:
        defaultMode: 420
        items:
          - key: {{ .Values.auth.configSecret.key }}
            path: {{ include "authentication-config.file" . }}
        secretName: {{ .Values.auth.configSecret.name }}
    {{- end }}
    {{- if .Values.dataSource.caSecret.name }}
    - path: /var/lib/k0s/kine-ca
      secret:
        defaultMode: 420
        items:
          - key: {{ .Values.dataSource.caSecret.key }}
            path: ca.crt
        secretName: {{ .Values.dataSource.caSecret.name }}
    {{- end }}
  {{- end }}
  {{- if .Values.dataSource.kineDataSourceSecretName }}
  kineDataSourceSecretName: {{ .Values.dataSource.kineDataSourceSecretName }}
  {{- end }}
  controllerPlaneFlags:
    - --enable-cloud-provider=true
    - --debug=true
    {{- range $arg := .Values.k0smotron.controllerPlaneFlags }}
    - {{ toYaml $arg }}
    {{- end }}
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      api:
        extraArgs:
          {{- if .Values.auth.configSecret.name }}
          authentication-config: {{ include "authentication-config.fullpath" . }}
          {{- end }}
          {{- with .Values.k0s.api.extraArgs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.k0s.network }}
      network: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if $global.registry }}
      images:
        repository: "{{ $global.registry }}"
      {{- end }}
      extensions:
        helm:
          repositories:
          {{- if not $global.registry }}
            - name: mirantis
              url: https://charts.mirantis.com
            - name: azuredisk-csi-driver
              url: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
          {{- else }}
            - name: global-registry
              url: oci://{{ regexReplaceAll "/.*" $global.registry "" }}
              {{- if $global.registryCertSecret }}
              caFile: /usr/local/share/ca-certificates/registry/ca.crt
              {{- end }}
          {{- end }}
          charts:
            - name: cloud-provider-azure
              namespace: kube-system
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/charts/cloud-provider-azure
              {{- else }}
              chartname: mirantis/cloud-provider-azure
              {{- end }}
              version: 1.31.2
              order: 1
              values: |
                cloudControllerManager:
                  cloudConfigSecretName: azure-cloud-provider
                  nodeSelector:
                    node-role.kubernetes.io/control-plane: null
                  {{- if $global.registry }}
                  imageRepository: {{ $global.registry }}
                  {{- end }}
                  imageTag: v1.32.4
                cloudNodeManager:
                  imageTag: v1.32.4
                {{- if $global.registry }}
                  imageRepository: {{ $global.registry }}
                {{- end }}
            - name: azuredisk-csi-driver
              namespace: kube-system
              {{- if $global.registry }}
              chartname: oci://{{ $global.registry }}/charts/azuredisk-csi-driver
              {{- else }}
              chartname: azuredisk-csi-driver/azuredisk-csi-driver
              {{- end }}
              version: v1.30.3
              order: 2
              values: |
                {{- if $global.registry }}
                image:
                  baseRepo: {{ $global.registry }}
                  azuredisk:
                    repository: /kubernetes-csi/azuredisk-csi
                  csiProvisioner:
                    repository: /kubernetes-csi/csi-provisioner
                  csiAttacher:
                    repository: /kubernetes-csi/csi-attacher
                  csiResizer:
                    repository: /kubernetes-csi/csi-resizer
                  livenessProbe:
                    repository: /kubernetes-csi/livenessprobe
                  nodeDriverRegistrar:
                    repository: /kubernetes-csi/csi-node-driver-registrar
                snapshot:
                  image:
                    csiSnapshotter:
                      repository: /kubernetes-csi/csi-snapshotter
                    csiSnapshotController:
                      repository: /kubernetes-csi/snapshot-controller
                {{- end }}
                controller:
                  cloudConfigSecretName: azure-cloud-provider
                node:
                  cloudConfigSecretName: azure-cloud-provider
                linux:
                  kubelet: "/var/lib/k0s/kubelet"
