apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderInterface
metadata:
  name: cluster-api-provider-aws
  annotations:
    helm.sh/resource-policy: keep
spec:
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta2
      kind: AWSCluster
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta2
      kind: AWSManagedCluster
  clusterIdentityKinds:
    - AWSClusterStaticIdentity
    - AWSClusterRoleIdentity
    - AWSClusterControllerIdentity
  description: "AWS infrastructure provider for Cluster API"
