name: Setup Go Cache
description: Setup Go and optionally restore Go module and linter cache, depending on USE_CACHE env var

inputs:
  go-version-file:
    description: Path to go.mod or file containing Go version
    required: false
    default: 'go.mod'

  include-lint-cache:
    description: Whether to include GolangCI-Lint cache
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache: false

    - name: Prepare cache paths
      id: paths
      shell: bash
      run: |
        echo "mod=~/go/pkg/mod" >> "$GITHUB_OUTPUT"
        if [ "${{ inputs.include-lint-cache }}" = "true" ]; then
          echo "lint=~/.cache/golangci-lint" >> "$GITHUB_OUTPUT"
        fi

    - name: Conditionally restore Go cache
      shell: bash
      env:
        USE_CACHE: ${{ env.USE_CACHE }}
      run: |
        echo "USE_CACHE is: ${USE_CACHE:-unset}"
        if [ "${USE_CACHE:-true}" = "false" ]; then
          exit 0
        fi

        echo "cache_key=${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}" >> $GITHUB_ENV

    - name: Restore Go cache (actual cache step)
      if: env.cache_key != ''
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.paths.outputs.mod }}
          ${{ steps.paths.outputs.lint }}
        key: ${{ env.cache_key }}
        restore-keys: |
          ${{ runner.os }}-go-
