name: Cleanup Caches on Closed Pull Requests

on:
  pull_request_target:
    types:
      - closed

jobs:
  cleanup:
    name: Delete PR-specific caches
    runs-on: ubuntu-latest
    permissions:
      actions: write  # required to delete caches
    steps:
      - name: Delete caches for this PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
        shell: bash
        run: |
          echo "Fetching cache entries for PR branch: $BRANCH"
          cacheKeysForPR=$(gh cache list --ref "$BRANCH" --limit 100 --json id --jq '.[].id')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting cache entries..."
          for cacheKey in $cacheKeysForPR; do
            echo "Deleting cache with ID: $cacheKey"
            gh cache delete "$cacheKey"
          done
          echo "Cleanup completed"
